### ISSUE TITLE
Broadcast rounds not supported

### ISSUE THREAD

**Issue by mtvec** [ZackClements/berserk#14]
The implementation of the [broadcast API](https://lichess.org/api#tag/Broadcasts) seems outdated as it doesn't support rounds.

More specifically, the following endpoints are not implemented:
- [Create a round](https://lichess.org/api#operation/broadcastRoundCreate): `/broadcast/{broadcastTournamentId}/new`
- [Get a round](https://lichess.org/api#operation/broadcastRoundGet): `/broadcast/{broadcastTournamentSlug}/{broadcastRoundSlug}/{broadcastRoundId}`
- [Update round](https://lichess.org/api#operation/broadcastRoundUpdate): `/broadcast/round/{broadcastRoundId}/edit`

And these are outdated:
- [Create broadcast](https://lichess.org/api#operation/broadcastTourCreate), [Update broadcast](https://lichess.org/api#operation/broadcastTourUpdate)
  - The `syncUrl`, `credit`, `startsAt`, and `throttle` parameters don't exist anymore.
- [Push PGN](https://lichess.org/api#operation/broadcastPush)
  - Endpoint is now `/broadcast/round/{broadcastRoundId}/push`

**Comment by ZackClements** [comment]
Updated, thanks for reporting
